### ISSUE TITLE
Any way to re-synthesis audio?

### ISSUE THREAD

**Issue by puppylpg** [jackaduma/CycleGAN-VC2#5]
Is there any way to re-synthesis new audio using the trained model? I don't know whether I miss some info or the info such as `synthesis.py` is left out. 
Thanks in advance.

**Comment by keishatsai** [comment]
Do you mean that you want to test the model? Like inferencing the test audios?
If so, you can write your own (so as I did). You got model structure, and it should be not difficult to write one.
