### ISSUE TITLE
有没有兴趣复现CycleGAN-VC3?

### ISSUE THREAD

**Issue by splinter21** [jackaduma/CycleGAN-VC2#6]
https://arxiv.org/abs/2010.11672
Accepted to Interspeech 2020.

**Comment by jackaduma** [comment]
I will try ~ tks

**Comment by jackaduma** [comment]
> https://arxiv.org/abs/2010.11672
> Accepted to Interspeech 2020.

请参看我的新项目   https://github.com/jackaduma/CycleGAN-VC3 谢谢

**Comment by splinter21** [comment]
> > https://arxiv.org/abs/2010.11672
> > Accepted to Interspeech 2020.
> 
> 请参看我的新项目 https://github.com/jackaduma/CycleGAN-VC3 谢谢

get
感谢！
